# action.yml
name: 'SQL Guardian'
author: 'Diego Sousa'
description: 'Review SQL changed and modified files using pgsql-parser.'

outputs:
  sql_errors:
    description: "Returns the list of errors found inside all modified SQL files"

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'shield'
  color: 'blue'
