name: SQL Guardian

on: [pull_request]

jobs:
  sql-review:
    runs-on: ubuntu-latest
    name: SQL Guardian
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run SQL Guardian
        id: sql_guardian
        uses: ./
        with:
          SQL_FILES: ./samples/arquivo1.sql ./samples/arquivo2.sql

      - name: Echo SQL Errors
        run: echo "${{ steps.sql_guardian.outputs.sql_errors }}"
