# action.yml
name: 'SQL Guardian'
author: 'Diego Sousa'
description: 'Review SQL pull requests based on specific rules.'
inputs:
  some-random-input:
    description: 'Some random input'
    required: true
    default: 'Random'
runs:
  using: "composite"
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42
    - name: Exec SQL Guard
      run: $GITHUB_ACTION_PATH/action-entrypoint.sh
      shell: bash
      env:
        ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
        CHANGED_AND_MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
