# action.yml
name: 'SQL Guardian'
author: 'Diego Sousa'
description: 'Review SQL pull requests based on specific rules.'
runs:
  using: "composite"
  steps:
    # Get changed files
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42

    # Exec SQL Guard
    - name: Exec SQL Guard
      id: sql-guard
      run: bun $GITHUB_ACTION_PATH/action-entrypoint.ts
      shell: bash
      env:
        # CHANGED_AND_MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
        CHANGED_AND_MODIFIED_FILES: ${{ vars.all_changed_and_modified_files }}
branding:
  icon: 'shield'
  color: 'blue'
