name: Sql Guardian Tester

on:
  push:
    branches:
      - main

jobs:
  local-job:
    runs-on: ubuntu-latest

    steps:
      - uses: AutoModality/action-clean@v1

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Run SQL Guardian
        uses: sousadiego11/sql-guardian@latest
